almost complete

diff --git a/multi-volume-backup b/multi-volume-backup
--- a/multi-volume-backup
+++ b/multi-volume-backup
@@ -2,7 +2,6 @@
 # A smart multi-volume backup script based on `tar`.
 
 prog=$0
-prog_name=$(basename "$0")
 cmd=$1
 
 MVB_WORK_DIR=${MVB_WORK_DIR:-"/tmp"}
@@ -14,16 +13,19 @@ else
 fi
 
 usage() {
+    local prog_name
+    prog_name=$(basename "$0")
+
     echo "Usage:"
     echo "  $prog_name backup <source path> <dest path with volume name prefix> <volume size> <snar file path>"
-    echo "  $prog_name restore <source path with volume name prefix> <dest path>"
+    echo "  $prog_name restore <first volume path> <dest path>"
     echo
     echo "Note:"
     echo "  snar file record the filelist to achive incremental backup"
     echo
     echo "Example:"
     echo "  multi-volume-backup backup /data /mnt/bak/full_backup- 100G /data.snar"
-    echo "  multi-volume-backup restore /mnt/bak/full_backup- /data"
+    echo "  multi-volume-backup restore /mnt/bak/full_backup-1.tar /data"
     exit 1
 }
 
@@ -85,23 +87,18 @@ do_backup() {
     fi
 
     # reader
-    logi "Starting backgroud reader(tar) to read data and write to data channel"
+    logi "Starting reader(tar) to read data and write to data channel"
     # use environment variables to pass arguments to tar script
-    MVB_CMD="__change_volume" \
-    MVB_DST_DIR="$dst_dir" \
-    MVB_VOL_SIZE="$size" \
-    MVB_SIGNAL_CH="$signal_channel" \
-    tar -cM -v -H posix -L "$size" -F "$prog" -f "$data_channel" -g "$snar" "$src" > "$MVB_WORK_DIR/tar.log" &
-    local reader_pid=$!
-
-    # wait any worker exit
-    # TODO
-    logi "Waiting for reader complete"
-    wait "$reader_pid"
-
-    # notify writer complete
-    logi "Backgroud reader exit with code $?, notify writer"
-    echo "DONE" > "$signal_channel"
+    export MVB_CMD="__change_volume"
+    export MVB_DST_PREFIX="$dst_prefix"
+    export MVB_VOL_SIZE="$size"
+    export MVB_DATA_CH="$data_channel"
+    export MVB_SIGNAL_CH="$signal_channel"
+    tar -cM -v -H posix -L "$size" -F "$prog" -f "$data_channel" -g "$snar" "$src"
+    
+    # notify writer
+    logi "tar process exit with code $?, notify backgroud writer"
+    echo "EXIT" | timeout 10 tee "$signal_channel"
     if ! timeout 10 wait "$writer_pid"; then
         logi "Writer not exit after timeout, kill it(pid=$writer_pid)"
         kill -9 "$writer_pid"
@@ -132,11 +129,11 @@ do_recv() {
         logi "Finish writing to $dst, sha256sum: $checksum"
         echo "$checksum" > "$dst.sha256sum"
 
-        logi "Waiting for next volume"
+        logi "Waiting for next volume signal"
         local sig
         sig=$(cat "$signal_channel")
-        if [ "$sig" = "DONE" ]; then
-            logi "Receive DONE signal, exit"
+        if [ "$sig" = "EXIT" ]; then
+            logi "Receive EXIT signal, exit"
             exit 0
         fi
 
@@ -145,11 +142,94 @@ do_recv() {
 }
 
 do_restore() {
-    echo
+    local src="$1"
+    local dst="$2"
+
+    [ -z "$src" ] || usage
+    [ -z "$dst" ] || usage
+
+    tar -xM -v -F "$prog" -f "$src" "$dst"
+}
+
+wait_user_confirm() {
+    local answer
+    echo "Please mount a new disk/tape to correct mountpoint."
+    while true; do
+        read -r -p "Are new disk/tape mounted?(Y/n): " answer
+        if [ "$answer" = "Y" ]; then
+            return 0
+        fi
+    done
+}
+
+get_next_backup_volume() {
+    # check environment
+    [ -n "$MVB_DST_PREFIX" ] || logf "MVB_DST_PREFIX CANNOT be empty"
+    [ -n "$MVB_VOL_SIZE" ] || logf "MVB_VOL_SIZE CANNOT be empty"
+    [ -n "$MVB_DATA_CH" ] || logf "MVB_DATA_CH CANNOT be empty"
+
+    {
+        local dst_prefix=$MVB_DST_PREFIX
+        local dst_dir
+        dst_dir=$(dirname "$dst_prefix")
+
+        local size_num=${MVB_VOL_SIZE%?}
+        local size_unit=${MVB_VOL_SIZE:-1}
+        local avail
+
+        # get availiable space of dest
+        avail=$(df -B"$size_unit" "$dst_dir" | awk 'NR==2 {print $4}')
+        avail=${avail%?}
+        if [ -z "$avail" ]; then
+            loge "Failed to get availiable space of $dst_dir"
+            wait_user_confirm
+        elif [ "$avail" -le "$size_num" ]; then
+            loge "Availiable space of $dst_dir too small"
+            wait_user_confirm
+        fi
+    } 1>&2
+
+    echo "$MVB_DATA_CH"
+    return 0
+}
+
+get_next_restore_volume() {
+    local prefix=${TAR_ARCHIVE%-*}
+    local suffix=${TAR_ARCHIVE##*-}
+    local ext=${suffix#*.}
+    local next_vol_name="${prefix}${TAR_VOLUME}.${ext}"
+
+    {
+        while ! [ -r "$next_vol_name" ]; do
+            loge "$next_vol_name is not readable"
+            wait_user_confirm
+        done
+    } 1>&2
+
+    echo "$next_vol_name"
 }
 
 do_change_volume() {
-    echo
+    log_tag="change_volume"
+    local next_vol_name
+
+    logi "Preparing volume $TAR_VOLUME"
+
+    case "$TAR_SUBCOMMAND" in
+    -c)
+        next_vol_name=$(get_next_backup_volume)
+        # resume writer
+        echo "RESUME" > "$MVB_SIGNAL_CH"
+        ;;
+    -d|-x|-t)
+        next_vol_name=$(get_next_restore_volume)
+        ;;
+    *)
+        exit 1
+        ;;
+    esac
+
+    echo "$next_vol_name" >&"$TAR_FD"
 }
 
 case "$cmd" in
@@ -160,7 +240,7 @@ __recv)
     do_recv "$@"
     ;;
 restore)
-    do_restore
+    do_restore "$@"
     ;;
 __change_volume)
     do_change_volume
